### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [Mexassi/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose one.

Please also consider renaming the repo to something less generic - maybe mexassi-zsh-theme?

**Comment by Mexassi** [comment]
Thanks for reaching out and for your guidance regarding choosing a license. I have added a license and renamed the repo to something less generic as you suggested.

**Comment by unixorn** [comment]
Thanks. Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/724
